// Hand-authored English word families. Targets are deliberately curated;
// this file is original project data, not a third-party dictionary extract.
// Each row: wheel | required words | extra accepted words | scenery.
const CAMPAIGN = `
APPLE|APPLE PALE LEAP PEAL LAP|PAL ALE PEA PLEA|harvest
PEARS|PEARS SPEAR PEAR SPARE PARE|RAP RAPS ARE EAR ERA SEA SPA|harvest
GRAPE|GRAPE PAGER PAGE RAGE REAP|PEAR PARE GAP PEG RAG AGE EAR|harvest
PEACH|PEACH CHEAP EACH HEAP PACE|ACE APE CAP CHAP PEA|harvest
LEMON|LEMON MELON LONE OMEN MOLE|ONE ELM MEN|harvest
BREAD|BREAD BARED BEARD BARE READ|ARE BAD BAR BED BRA DAB DEAR EAR ERA RED|harvest
PLUMS|PLUMS PLUM LUMP SLUM SUM|PUS UPS|harvest
OLIVES|OLIVES OLIVE LIVES VEILS SOLVE|LIVE LOVE LIE OIL SOIL VILE VISE|harvest
WHEAT|WHEAT WHAT HEAT THAW WET|ATE EAT TEA HAT HEW AWE|harvest
GRAIN|GRAIN GAIN RAIN RING GRIN|AIR RAN RAG RIG GIN|harvest
BEANS|BEANS BEAN BASE SANE BAN|BANS NABS NAB SEA|harvest
MANGO|MANGO AMONG MOAN NAG MAN|AGO NAG MAG|harvest
ORANGE|ORANGE ORGAN GROAN RANGE EARN|AGE AGO ARE EAR EGO RAN RAG|harvest
CHERRY|CHERRY CRY RYE HER HEY|ERR|flowers
CARROT|CARROT ACTOR CART COAT TACO|RAT TAR ART ARC CAR CAT COT|harvest
POTATO|POTATO PAT TOO TOP OAT|POT TAP APT|harvest
TOMATO|TOMATO MOAT ATOM MOTTO TOO|MAT OAT TAM TOM|harvest
TURNIP|TURNIP PRINT TURN TRIP PUNT|PIN PIT RIP RUT RUN TIN NUT TIP|harvest
RADISH|RADISH HARD HAIR RAID DASH|AID AIR ASH HAD HID HIS RID SAD|harvest
CELERY|CELERY REEL LEER RELY LYRE|EEL LEE RYE CRY EYE|harvest
COTTON|COTTON COOT ONTO TON COT|TON TOO NOT|harvest
LINEN|LINEN LINE NINE INN LIE|NIL|flowers
SILKEN|SILKEN LIKEN LIKES LINES SINK|INK KIN LIE SIN SKI ILK|flowers
SATIN|SATIN SAINT STAIN TANS ANTS|ANT SAT SIT SIN TAN TIN NIT ITS|flowers
CANDLE|CANDLE CLEAN DANCE LANCE DEAL|CAN DEN END LAD LEAD LAND LEND|moonlight
LANTERN|LANTERN LEARN ALTER LATER RENTAL|ANT RAN RAT TAN TAR TEAR NEAR RENT|moonlight
PLANET|PLANET PLANE PANEL PLANT PETAL|ANT ATE EAT LAP NAP NET PAN PEN|moonlight
COMETS|COMETS COMET COMES STEM COST|COT MET SET TOE SOME MOST|moonlight
METEOR|METEOR REMOTE METER MORE MEET|MET ORE ROT TOE TREE TORE|moonlight
STARRY|STARRY STAY STAR RATS ART|RAT TAR TRY RAY SAT|moonlight
SOLAR|SOLAR SOAR OARS ALSO ORAL|OAR ORA RAS|sunrise
SHINES|SHINES SHINE SHINS HIS HENS|HEN HIS SHE SIN HIE|sunrise
BRIGHT|BRIGHT BIRTH RIGHT GIRTH GRIT BIG|BIT HIT RIB RIG|sunrise
SHADOW|SHADOW SHOW WASH DASH HAD HAS|HAD HOW SAD SAW WHO|moonlight
SILVER|SILVER SLIVER LIVER LIVES EVIL RISE|LIE SIR VIE VEIL VILE|moonlight
GOLDEN|GOLDEN LONGED LODGE OGLE GOLD DOG|DOE DEN END GOD LOG NOD OLD|sunrise
AMBER|AMBER BREAM BEAM BEAR BARE ARE|ARM BAR BRA EAR ERA RAM|sunrise
CORAL|CORAL CAROL COAL ORAL ORCA ARC|CAR OAR|brook
SHELLS|SHELLS SHELL SELLS LESS SELL SHE|ELL ELS|brook
SHORES|SHORES SHORE HORSE ROSES SHOE SORE|HER HOE ORE ROE SHE ROSE|brook
STREAM|STREAM MASTER TAMER SMART STEAM ARM|ART ATE EAR EAT ERA MAT MET RAM|brook
RIPPLE|RIPPLE PIPER RIPE PILE PERIL LIE|LIP PER PIE RIP|brook
WATERS|WATERS WATER SWEAT STRAW STARE ARE|ART ATE EAR EAT ERA RAT RAW SEA|brook
BREATH|BREATH EARTH HEART HATER BATHE ARE|ART ATE BAR BAT BET BRA EAR EAT ERA|alpine
WINTER|WINTER WRITE INTER INERT TWIN NET|NEW NIT TIE TIN TEN WIN WIT|alpine
SPRING|SPRING GRIPS RINGS SPIN GRIN GIN|NIP PIG PIN RIP RIG SIN SIP|seedlings
AUTUMN|AUTUMN AUNT TUNA NUT ANT TAN|MAT MAN TUN|harvest
SEASON|SEASON OASES NOSES SANE SONS ONE|SEA SON ASS|sunrise
FROZEN|FROZEN FROZE ZONE ZERO FERN FOR|FRO NOR ORE ROE ZEN|alpine
SNOWED|SNOWED OWNED ENDOW DOWNS NOSE DEN|DEW DOE END NEW NOD NOW ONE OWE|alpine
CLOUDY|CLOUDY CLOUD COULD COLD LOUD COD|COY CUD DUO OLD YOU|alpine
THUNDER|THUNDER HUNTER UNDER TREND HUNT DEN|DUE END HEN HER HUE HUT NET NUT|alpine
RAINBOW|RAINBOW BRAIN BROWN RAIN WORN AIR|BAN BAR BIN BOW BRA NAB NOR NOW|sunrise
FLOWERS|FLOWERS FLOWER LOWER WORSE FLOWS FEW|FOE FOR LOW ORE OWL ROW SOW|flowers
BLOSSOM|BLOSSOM BLOOMS BLOOM LOOMS MOSS LOB|BOO LOO MOB MOO SOB|flowers
NECTAR|NECTAR TRANCE CRANE REACT TRACE ACE|ACT ANT ARC ARE ART ATE CAN CAR|flowers
DAISIES|DAISIES ASIDE IDEAS AIDS SAID AID|DIE SEA SAD|flowers
ROSEBUD|ROSEBUD BORED BODES ROBED DOSE BED|BUD BUS DOE DUB DUE ODE ORE OUR|flowers
SEEDLING|SEEDLING SEEING SINGLE DESIGN SLIDE DEN|DIE DIG DIN EEL END GEL GIN LED|seedlings
SAPLING|SAPLING SIGNAL PLAINS GASP PAIN GAIN|AIL GAP GAS GIN LAP LIP NAG NAP|seedlings
FERRET|FERRET FREE TREE REEF FRET FEET|FEE FETE TEE|woodland
ACORNS|ACORNS ACORN CORNS SCORN SCAN ARC|CAN CAR CON NOR OAR RAN SAC SON|woodland
TIMBER|TIMBER BITE REMIT TIMER BITER BET|BIT IRE MET RIB RIM TIE|woodland
BEETLE|BEETLE BEE BELT BEET LET BET|BEE EEL LEE TEE|woodland
`;

const DAILY = `
RABBIT|RABBIT RABBI BAT BAIT BRAT|AIR ART BAR BAT BIT BRA RAT RIB TAB TAR|woodland
BADGER|BADGER BARGE BREAD GRADE BEARD|AGE ARE BAD BAG BAR BED BEG BRA DAB|woodland
OTTERS|OTTERS OTTER STORE TORTE REST|ORE ROE ROT SET TOE TOT|brook
HERONS|HERONS HERON SHORE HORSE SHONE|HEN HER HOE NOR ONE ORE ROE SHE SON|brook
ROBINS|ROBINS ROBIN IRONS BISON BORN|BIN ION NIB NOR RIB ROB SIN SIR SON|woodland
SPARROW|SPARROW ARROWS SPAR WARS WRAP|OAR PAR PAW RAP RAW ROW SAP SAW SOW|woodland
FINCHES|FINCHES FINCH CHINS SHINE FINE|CHI FIN HEN ICE SHE SIN HIS|woodland
FALCON|FALCON FLAN COAL CALF LOAF|CAN CON FAN OAF|woodland
EAGLES|EAGLES EAGLE GALES EASEL SAGE|AGE ALE EEL GEL LAG LEG SAG SEA|alpine
PIGEON|PIGEON PINE GONE OPEN PING|EGO GIN ION NIP ONE PEG PEN PIE PIG|woodland
WOLVES|WOLVES VOWELS WOVE LOVE SLOW|LOW OWE OWL SEW SOW VOW WOE|woodland
FOXTAIL|FOXTAIL FLOAT LOAF FAIL TAIL|FOX FAT FIT OIL OAT LIT TAX TOIL|woodland
TIGERS|TIGERS TIGER TRIES GRIST GRITS|GET IRE ITS RIG SET SIR SIT TIE|woodland
LIONS|LIONS LION LOINS SOIL IONS|ION NIL OIL SIN SON|sunrise
ZEBRAS|ZEBRAS ZEBRA BARES BRAZE BEARS|ARE BAR BRA EAR ERA SEA|sunrise
HOUNDS|HOUNDS HOUND SOUND SHUN DONS|DUN DUNS DUO DUOS NOD NODS NOSH SON SUN SOD|woodland
PONIES|PONIES SPINE PINES POISE NOISE|ION NIP ONE PEN PIE PIN SIN SIP SON|harvest
DONKEY|DONKEY DON YOKE NODE DONE|DEN DOE DYE END KEY NOD ONE YEN|harvest
CHICKS|CHICKS CHICK CHIC SICK HIS|CHI HIS ICK SKI|harvest
TURKEY|TURKEY TREK TRUE TYKE YURT|KEY RUE RUT RYE TRY|harvest
TURTLE|TURTLE UTTER TRUE LURE RULE|LET RUE RUT|brook
LIZARD|LIZARD LID LIAR RAID DIAL|AID AIL AIR LAD LID RAD RID|canyon
SNAKES|SNAKES SNAKE SNEAK SANE SANK|ASK SEA SAKES SAKE|canyon
SPIDER|SPIDER PRIDES PRIDE SPIRE RIDE|DIE DIP IRE PIE RED RID RIP SIR SIP|woodland
CRICKET|CRICKET TICKER TRICK TICK TREK|ICE IRE KIT TIE TIC|woodland
DRAGON|DRAGON GRAND GROAN ORGAN ROAD|ADO AND AGO DOG DON GOD NAG NOD OAR|canyon
CASTLE|CASTLE CLEATS LACES LEAST SLATE|ACE ACT ALE ATE CAT EAT LET SAT SEA|woodland
PALACE|PALACE PLACE PACE LACE CAPE|ACE ALE APE CAP LAP PAL PEA|flowers
BRIDGE|BRIDGE BRIDE RIDGE DIRGE BIRD|BED BEG BID BIG DIE DIG RED RIB RID|brook
CABINS|CABINS CABIN BASIN BASIC BANS|BAN BIN CAB CAN NAB NIB SAC SIN|woodland
TRAILS|TRAILS TRIALS STAIR TAILS LIARS|AIL AIR ART ITS LIT RAT SAT SIR SIT|woodland
PATHWAY|PATHWAY PATH WHAT THAW AWAY|APT HAT HAY PAT PAW PAY TAP WAY YAW|woodland
ISLAND|ISLAND SNAIL NAILS LAND LAID|AID AIL AND DIN LAD LID NIL SAD SIN|brook
VALLEY|VALLEY ALLY LEVY VEAL ALLEY|ALE ALL AYE LAY YEA|woodland
MEADOW|MEADOW MOWED WADE MADE DOME|ADO AWE DAM DEW DOE MAD MAW MOW ODE|flowers
PRAIRIE|PRAIRIE REPAIR RAPIER RIPE PAIR|AIR ARE APE EAR ERA IRE PAR PEA PER PIE|sunrise
HIKERS|HIKERS HIKER HIRES SHIRE SKIER|HIS HER IRE RISE RISK SHE SIR|woodland
VALLEYS|VALLEYS SLAVE VALLEY ALLEYS SAVE|ALE ALL AYE LAY LEA SAY SEA SLY YES|woodland
SUMMITS|SUMMITS SUMMIT MISTS MIST MUST|ITS MUM SIM SIT SUM|alpine
PEAKS|PEAKS SPEAK PEAS PEAK SAKE|APE ASK ASP PEA SAP SEA SPA|alpine
DESERT|DESERT RESTED TREES STEER DETER|DEE ERE RED SEE SET TEE|canyon
`;

function parseRows(text, prefix) {
  return text.trim().split('\n').map((row, index) => {
    const [letters, words, bonus, scene] = row.split('|');
    return { id: `${prefix}-${index + 1}`, title: `Clearing ${index + 1}`, letters,
      targets: words.split(' '), bonus: [...new Set(bonus.split(' '))].filter(word => !words.split(' ').includes(word)), scene };
  });
}
export const newCampaignContent = parseRows(CAMPAIGN, 'grove');
export const newDailyContent = parseRows(DAILY, 'daily');
export const contentWords = [...newCampaignContent, ...newDailyContent].flatMap(level => [...level.targets, ...level.bonus]);
