// Authored word families for Second Garden and the expanded daily rotation.
// Rows are wheel | required words | accepted extras | scenery.
const SECOND_GARDEN = `
IRISES|IRISES RISES SIRES RISE SIRE IRIS|SIR IRE SIS|flowers
TULIPS|TULIPS TULIP SPLIT SPILT LISP LIPS|PIT SIT SIP TIP|flowers
ASTER|ASTER STARE TEARS RATES TARES STAR|ART RAT SEA TEA|flowers
PETUNIAS|PETUNIAS PAINTS SPINE UNITE SUITE TUNES|ANT ATE NAP PAN PIN|flowers
PANSIES|PANSIES SPINES SPINE SPANS SANE PINE|PAN PIN NAP SIP SIN|flowers
GENTLE|GENTLE GLEN GLEE LENT GENE TEEN|GET NET TEN EEL|flowers
VINES|VINES VINE VEIN VEINS SINE VISE|SIN VIE|seedlings
VIOLETS|VIOLETS OLIVES TOILS STOVE LIVES VIOLET|OIL LIE TIE TOE|flowers
DAFFODIL|DAFFODIL DIAL FOIL LOAD LOAF FAIL|AID AIL LAD LID|flowers
ORCHIDS|ORCHIDS CHORDS CHOIRS ORCHID RICH DISH|COD HID RID SIR|flowers
AZALEAS|AZALEAS AZALEA SEAL SALE ALES ZEAL|ALE SEA LEA|flowers
LILACS|LILACS LILAC CALL ILLS SAIL AILS|AIL ILL SIC|flowers
ROSES|ROSES SORES SORE ROSE ORES ROES|ORE ROE|flowers
BERRIES|BERRIES BRIERS BRIER BEERS BIER RISE|BEE IRE RIB SIR|harvest
PEACHES|PEACHES PEACH CHEAP CHASE HEAPS SHAPE|ACE APE CAP PEA|harvest
APPLES|APPLES APPLE PALES LEAPS PLEAS LAPSE|ALE APE LAP PAL|harvest
PLANTED|PLANTED PLANET PANEL PLANT PETAL PLANE|ANT ATE DEN END|seedlings
TENDED|TENDED DENTED ENDED NEED TEEN DENT|DEN END NET TEN|seedlings
WATERED|WATERED WATER TRADE TREAD WADER RATED|ARE ATE DEW EAR|brook
PERGOLA|PERGOLA PAROLE PEARL LARGE REGAL GLARE|AGE ALE APE GAP|seedlings
GARDENS|GARDENS DANGER GANDER GRADES RANGES GRAND|AGE AND ARE DEN|seedlings
BLOOMED|BLOOMED BLOOM MODEL LOBED DOOM DEMO|BED DOE ELM MOB|flowers
HARVESTS|HARVESTS SHAVERS HEARTS EARTHS STARES SHARES|ARE ART ASH ATE|harvest
RESTFUL|RESTFUL RESULT FLUTE LURES RULES TRUE|ELF LET RUE RUT SET|moonlight
`;
const DAILY_EXPANSION = `
SINGERS|SINGERS SINGER REIGNS SINGE RINGS|GIN IRE RIG SIN SIR|woodland
PAINTER|PAINTER PERTAIN PAINT TRAIN INERT|ANT AIR APE ART EAR|flowers
WRITER|WRITER WRITE RITE TIRE WIRE|IRE TIE WIT|moonlight
READER|READER REREAD READ DEAR DARE|ARE EAR ERA RED|moonlight
POETRY|POETRY POET TYPE ROPE TORE|PET POT PRY RYE TOE|moonlight
MUSICAL|MUSICAL MUSIC CLAIM CALM CLAM ALUM|AIL AIM CAM LAM SUM|sunrise
DANCER|DANCER DANCE CRANE CARED RACE|ACE AND ARC ARE CAR|flowers
SINGER|SINGER REIGNS SIGN RING RISE|GIN IRE RIG SIN SIR|woodland
PLAYER|PLAYER PEARL REPLAY LAYER RELAY|ALE APE ARE EAR ERA|flowers
ARTIST|ARTIST STRAIT START STAIR TRAIT|AIR ART ITS RAT SAT|flowers
PASTEL|PASTEL PLATES STAPLE LEAST SLATE|ALE APE ATE LAP PAL|flowers
CANVASS|CANVASS CANVAS CANS VANS SCAN|CAN VAN SAC|flowers
SCULPT|SCULPT CULT CUPS PLUS LUST|CUP CUT PUT SUP|woodland
PENCIL|PENCIL CLIP PILE PINE NICE|ICE LIE NIP PEN PIE|woodland
PAPERS|PAPERS PAPER SPEAR SPARE PEARS|APE ARE ASP EAR ERA|moonlight
INKWELL|INKWELL WELL WINK LINK LIEN|ELK ILL INK KIN NIL|moonlight
NOTEPAD|NOTEPAD ADOPT NOTED TONED PANT|ADO AND ANT APE ATE|moonlight
BOOKLET|BOOKLET BLOKE BOOT BOLT LOOK|BET ELK LET LOB LOT|moonlight
STORIES|STORIES TRIES RITES TIRES SORT|IRE ITS ORE ROT SET|moonlight
NOVELS|NOVELS NOVEL LONES LOVES SOLVE|EON ONE OLE SON|moonlight
FABLES|FABLES FABLE BALES FALSE FLEAS|ALE ABS LAB LEA SEA|woodland
LEGEND|LEGEND GLEN NEED LEND EDGE|DEN EEL END GEL LEG|woodland
HISTORY|HISTORY STORY SHORT SHIRT HOST|HIS HIT ITS SIR TRY|woodland
FANTASY|FANTASY FANS STAY FAST NASTY|ANT ANY FAT FAN SAT|moonlight
DREAMS|DREAMS DREAM SMEAR ARMED DEARS|ARE ARM DAM EAR ERA|moonlight
SLEEPY|SLEEPY SLEEP PEELS EELS EYES|EEL EYE LEE PEE YES|moonlight
COZIER|COZIER COIR CORE RICE ZERO|ICE IRE ORE|moonlight
QUIETER|QUIETER QUIET QUITE TREE TIER|IRE TIE RUE|moonlight
CALMER|CALMER CAMEL CLEAR REALM CREAM|ACE ALE ARC ARE ARM|brook
GENTLER|GENTLER GENTLE GREEN ENTER GLEN|EEL GEL GET LEG NET|flowers
BRISKLY|BRISKLY BRISK RISK SILKY SILK|ILK SKY SIR SKI|sunrise
HAPPENS|HAPPENS HAPPEN SHAPE HEAPS PHASE|APE ASH HEN NAP PAN|sunrise
SMILES|SMILES SMILE SLIME LIMES MILES|ELM LIE SIM IS|sunrise
LAUGHTER|LAUGHTER GATHER LATHER HALTER GLARE|AGE ALE ALT ARE ART|sunrise
FRIENDS|FRIENDS FRIEND FIND FIRED FINES|DEN DIE DIN END FED|woodland
FAMILY|FAMILY FILMY FILM MAIL FAIL|AIL AIM FLY LAY MAY|harvest
BASKET|BASKET BEAKS BEAST SKATE STAKE|ATE ASK BAT BET SEA|harvest
BLANKET|BLANKET BLEAK LEANT TAKEN TABLE|ANT ATE BAN BAT BET|harvest
TEAPOT|TEAPOT POET TAPE PATE TEAT|APE APT ATE EAT PAT|harvest
KITCHEN|KITCHEN THICK KETCH ETHIC CHINE|HEN HIT ICE KIT NET|harvest
COOKIES|COOKIES COOKIE COOKS COOS SOCK|COO ICE SIC SKI|harvest
BISCUIT|BISCUIT CUBIT BITS SUIT CUTS|BIT BUS BUT CUB CUT|harvest
CUPCAKE|CUPCAKE CAKE CAPE PACK PUCE|ACE APE CAP CUP PEA|harvest
PANCAKE|PANCAKE CAKE CANE PANE NECK|ACE APE CAN CAP NAP|harvest
WAFFLES|WAFFLES WAFFLE FLEAS FALSE FLAW|ALE AWE ELF FEW LAW|harvest
HONEY|HONEY HONE YEN ONE HEY|HEN HOE EON|harvest
CEREALS|CEREALS CEREAL CLEAR LACER SCALE|ACE ALE ARC ARE CAR|harvest
YOGURT|YOGURT GOUT TOUR ROUT YOUR|GOT GUY GUT OUR OUT|harvest
JUICES|JUICES JUICE CUES ICES CUE|ICE SIC JUS|harvest
`;
function parse(text, prefix) {
  return text.trim().split("\n").map((row, index) => {
    const [letters, targets, bonus, scene] = row.split("|");
    const words = targets.split(" ");
    return { id: `${prefix}-${index + 1}`, letters, targets: words,
      bonus: [...new Set(bonus.split(" "))].filter(word => !words.includes(word)), scene };
  });
}
export const secondGardenContent = parse(SECOND_GARDEN, "second");
export const expandedDailyContent = parse(DAILY_EXPANSION, "daily-expanded");
export const progressionWords = [...secondGardenContent, ...expandedDailyContent].flatMap(level => [...level.targets, ...level.bonus]);
